[project]
name = "alodokter-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scrapy>=2.12.0",
    "selenium>=4.31.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
